### ISSUE TITLE
Different MacOS Installation Location

### ISSUE THREAD

**Issue by plainasday** [ScanuNicco/Modern-ThunderBird#2]
This is really well done, thank you for creating some continuity between Firefox and Tunderbird. 

For me on MacOS, the location that I had to place `chrome/userChrome.css` in was `Users/<USERNAME>/Library/Thunderbird/Profiles/XXXXXXX.default-XXXXXXX` not `Users/<USERNAME>/Library/Application Support/Thunderbird/Profiles/XXXXXXX.default-XXXXXXX`.

**Comment by ScanuNicco** [comment]
Thanks for letting me know! I've updated the readme with the correct file path.
