### ISSUE TITLE
How did you customize your Linux like Windows?

### ISSUE THREAD

**Issue by xmha97** [ScanuNicco/Modern-ThunderBird#3]
How did you customize your Linux like Windows?
![Linux](https://raw.githubusercontent.com/ScanuNicco/Modern-ThunderBird/main/Screenshots/screen2.webp)

**Comment by ScanuNicco** [comment]
I just followed a guide for how to make KDE look like Windows 11. There's already a bunch of Windows themes on the KDE store so you don't even have to use the terminal or even download anything. I don't remember exactly which one I used but [this one](https://mashtips.com/make-linux-look-like-windows-11/) seems good. There's also some guides that go way farther than that one if you want to make the file manager and the system tray look exactly like windows.

**Comment by xmha97** [comment]
OK, thanks.
