### ISSUE TITLE
Shadow on tab is missing

### ISSUE THREAD

**Issue by danjaredg** [ScanuNicco/Modern-ThunderBird#4]
Hi, this css of thunderbird is grate, but in firefox there is a light shadow in selected tab, may be you can add this style in the userChrome.css

.tab-background[selected="true"] {
    box-shadow: 0px 0px 4px #888888;
}

**Comment by ScanuNicco** [comment]
Unfortunately adding a static color as the background doesn't look great on the dark theme. I could use --tabs-border-color but the shadow is much more subtle that way.

**Comment by ScanuNicco** [comment]
I can't believe I didn't figure this out in the first place but there is a way to detect whether a theme is light or dark using the media tag and set a css variable accordingly. Sorry it took so long, but it's all working in the latest commit. 

Here's some screenshots:
![image](https://user-images.githubusercontent.com/30136040/206356800-68260b43-7428-432e-a474-a77703f36c0b.png)
*Works with dark theme*
![image](https://user-images.githubusercontent.com/30136040/206357038-4cdaf307-16bf-46d5-b653-b8465fd1b870.png)
*Works with light theme*
![image](https://user-images.githubusercontent.com/30136040/206357203-8833fc4d-4542-43d1-be31-5ac843bc5df7.png)
*Works with custom themes (also URL bar is fixed)*
